### ISSUE TITLE
What is Synset ID? 

### ISSUE THREAD

**Issue by ritwikmishra** [cfiltnlp/challengeCognateFF#1]
Which wordNet are you referring to?

**Comment by dipteshkanojia** [comment]
We are referring to Synset ID's provided by the IndoWordnet KB. 
Each concept has a universal synset ID in IndoWordnet (language agnostic) which refers to a concept. All the individual Indian language WordNets follow the same Synset (Concept) ID.

Let me know if you have any other questions.
